### ISSUE TITLE
asm keyword not usable with -std=c99

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/target-mbed-gcc#10]
The `asm` keyword does not work with the `-std=c99` compiler switch.  An easy solution to this is to add `-fasm` to the command line as well.

**Comment by bremoran** [comment]
@bogdanm @autopulated

**Comment by autopulated** [comment]
OK, seems sane to add support for this, as it's a very common way of doing inline asm.

**Comment by 0xc0170** [comment]
@james, check the PR referenced here, there is further discussion. We should resolve this to be able to use inline asm, across compilers.

**Comment by bremoran** [comment]
Since I couldn't merge this change before beta, I resolved the issue I was seeing with a custom `*.cmake` to add the `-fasm`

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-910

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1004

**Comment by bremoran** [comment]
The right place to do something like this is probably compiler_polyfill.  I was able to resolve my particular issue in another way.
