### ISSUE TITLE
CMAKE_XXX_COMPILE_OBJECT needs updating to support CMake 3.4

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/target-mbed-gcc#24]
See https://github.com/ARMmbed/yotta/issues/672

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1863

**Comment by autopulated** [comment]
This issue was actually resolved in an earlier version, the report turned out to be due to a derived target still inheriting from an old version of this one.
